[package]
name = "net_trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ai_core = { git = "https://github.com/JTookey/AI_Core.git" }
eframe = "0.19.0"